AppWebBeachSA/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;

namespace AppWebBeachSA.Models
{
    public class Empleado
    {
        [Key]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        [Required]
        public int TipoUsuario { get; set; }

     
        [Required]
        public string Nombre { get; set; }

        [Required]
        [MinLength(8)]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [DataType(DataType.Password)]
        public bool Confirmar(string pw)
        {
            bool resultado = false;

            if (Password != null)
            {
                if (Password.Equals(pw))
                {
                    resultado = true;
                }

            }
            return resultado;
        }
    }
}

AppWebBeachSA/Controllers/HomeController.cs
using AppWebBeachSA.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppWebBeachSA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppWebBeachSA/Controllers/PaquetesController.cs
using Microsoft.AspNetCore.Mvc;
using AppWebBeachSA.Models;
using AppWebBeachSA.Data;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace AppWebBeachSA.Controllers
{
    public class PaquetesController : Controller
    {
        //Variable para utilizar la API
        private HotelAPI hotelAPI;

        //Variable para manejar las transacciones del protocolo HttpClient
        private HttpClient httpClient;


        public PaquetesController()
        {
            hotelAPI = new HotelAPI();
            httpClient = hotelAPI.Inicial();
        }

        /// <summary>
        /// metodo para obtener el token de autenticacion 
        /// </summary>
        /// <returns></returns>
        private AuthenticationHeaderValue AutorizacionToken()
        {
            var token = HttpContext.Session.GetString("token");
            AuthenticationHeaderValue authentication = null;

            if (token != null && token.Length != 0)
            {
                authentication = new AuthenticationHeaderValue("Bearer", token);
            }

            return authentication;
        }

        /// <summary>
        /// metodo encargado de obtener la lista de paquetes 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            List<Paquete> paquetes = new List<Paquete>();

            HttpResponseMessage response = await httpClient.GetAsync("/Paquetes/Listado");

            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                paquetes = JsonConvert.DeserializeObject<List<Paquete>>(resultado);
            }

            return View(paquetes);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Metodo encargado de agregar un paquete utilizando la API web
        /// </summary>
        /// <param name="paquete"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] Paquete paquete)
        {
            paquete.PaqueteID = 0;

            //se asigna el token de autorización
            httpClient.DefaultRequestHeaders.Authorization = AutorizacionToken();

            var agregar = httpClient.PostAsJsonAsync<Paquete>("/Paquetes/Agregar", paquete);
            await agregar; 

            var resultado = agregar.Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Mensaje"] = "No se logró registrar el paquete";
                return View(paquete);
            }

        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var paquete = new Paquete();

            HttpResponseMessage response = await httpClient.GetAsync($"/Paquetes/Buscar?id={id}");

            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                paquete = JsonConvert.DeserializeObject<Paquete>(resultado);
            }

            return View(paquete);
        }

        /// <summary>
        /// Metodo encargado de editar un paquete
        /// </summary>
        /// <param name="paquete"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind] Paquete paquete)
        {
            httpClient.DefaultRequestHeaders.Authorization = AutorizacionToken();

            var modificar = httpClient.PutAsJsonAsync<Paquete>("/Paquetes/Editar", paquete);
            await modificar;

            var resultado = modificar.Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Mensaje"] = "Datos incorrectos";

                if (resultado.StatusCode.ToString().Equals("Unauthorized"))
                {
                    return RedirectToAction("Login", "Empleados");
                }
                else
                {
                    return View(paquete);
                }
            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var paquete = new Paquete();

            HttpResponseMessage response = await httpClient.GetAsync($"/Paquetes/Buscar?id={id}");

            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                paquete = JsonConvert.DeserializeObject<Paquete>(resultado);
            }

            return View(paquete);
        }


        /// <summary>
        /// Metodo encargado de eliminar un paquete por medio del id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePack(int id)
        {
            httpClient.DefaultRequestHeaders.Authorization = AutorizacionToken();

            HttpResponseMessage response = await httpClient.DeleteAsync($"/Paquetes/Eliminar?id={id}");

            if (response.StatusCode.ToString().Equals("Unauthorized"))
            {
                return RedirectToAction("Login", "Empleados");
            }
            else
            { 
                return RedirectToAction("Index");
            }
        }


    }
}

AppWebBeachSA/Controllers/ReservacionesController.cs
using AppWebBeachSA.Data;
using AppWebBeachSA.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http.Headers;
using System.Security.Claims;

namespace AppWebBeachSA.Controllers
{
    public class ReservacionesController : Controller
    {
        private HotelAPI hotelAPI;

        //Variable para manejar las transacciones del protocolo HttpClient
        private HttpClient httpClient;

        public ReservacionesController()
        {
            hotelAPI = new HotelAPI();
            httpClient = hotelAPI.Inicial();
        }


        public async Task<IActionResult> Index()
        {
            List<Reservacion> reservaciones = new List<Reservacion>();
            int userId = int.Parse(User.FindFirstValue("UserId"));
            HttpResponseMessage response = await httpClient.GetAsync($"/Reservaciones/ReservacionesCliente?id={userId}");

            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                reservaciones = JsonConvert.DeserializeObject<List<Reservacion>>(resultado);
            }


            if (reservaciones != null) {
                 response = await httpClient.GetAsync("/Paquetes/Listado");
                List<Paquete> paquetes = new List<Paquete>();
                if (response.IsSuccessStatusCode)
                {
                    var resultado = response.Content.ReadAsStringAsync().Result;
                    paquetes = JsonConvert.DeserializeObject<List<Paquete>>(resultado);
                    ViewBag.Paquetes = paquetes;

                }
                return View(reservaciones);
            }

            return RedirectToAction("reservar");
        }

        [HttpGet]

        public async Task<IActionResult> reservar()
        {
            HttpResponseMessage response = await httpClient.GetAsync("/Paquetes/Listado");
            List<Paquete> paquetes = new List<Paquete>();
            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                  paquetes = JsonConvert.DeserializeObject<List<Paquete>>(resultado);
                ViewBag.Paquetes = paquetes;

            }
            var tipoCambio = await httpClient.GetAsync("https://apis.gometa.org/tdc/tdc.json");
            if (tipoCambio.IsSuccessStatusCode)
            {
                var content = await tipoCambio.Content.ReadAsStringAsync();
                dynamic data = JObject.Parse(content);
                ViewBag.tipoCambio= data.venta;
            }


                return View();

        }

        [HttpGet]

        public async Task<IActionResult> Paquete(int id)
        {
            HttpResponseMessage response = await httpClient.GetAsync($"/Paquetes/Buscar?id={id}");
            Paquete paquete = new Paquete();
            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                paquete = JsonConvert.DeserializeObject<Paquete>(resultado);
                ViewBag.paquete= paquete;
            }
            var image = await httpClient.GetAsync("/Paquetes/Listado");
            if (image.IsSuccessStatusCode)
            {
                var content =  image.Content.ReadAsStringAsync().Result;
                var paquetes = JsonConvert.DeserializeObject<List<Paquete>>(content);
                int indice = paquetes.FindIndex(paquete => paquete.PaqueteID == id);
                ViewBag.image = indice+"Room.jpg";
                ViewBag.today = DateTime.Now;

                return View();

            }

            return RedirectToAction("Index");


        }

        [HttpPost]
        private decimal CalcularDescuento(int noches)
        {
            if (noches >= 3 && noches <= 6)
                return 10;
            else if (noches >= 7 && noches <= 9)
                return 15;
            else if (noches >= 10 && noches <= 12)
                return 20;
            else if (noches >= 13)
                return 25;
            else
                return 0; 
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Paquete([Bind] Reservacion reservacion,int id)
        {
            
            HttpResponseMessage response = await httpClient.GetAsync($"/Paquetes/Buscar?id={id}");
            Paquete paquete = new Paquete();
            if (response.IsSuccessStatusCode)
            {
                var resultado = response.Content.ReadAsStringAsync().Result;
                paquete = JsonConvert.DeserializeObject<Paquete>(resultado);
                ViewBag.paquete = paquete;

            }

            var image = await httpClient.GetAsync("/Paquetes/Listado");
            if (image.IsSuccessStatusCode)
            {
                var content = image.Content.ReadAsStringAsync().Result;
                var paquetes = JsonConvert.DeserializeObject<List<Paquete>>(content);
                int indice = paquetes.FindIndex(paquete => paquete.PaqueteID == id);
                ViewBag.image = indice + "Room.jpg";
                ViewBag.today = DateTime.Now;


            }


            // Total sin descuento
            reservacion.TotalSinDescuento = reservacion.Noches * reservacion.Personas * paquete.PrecioPorPersonaPorNoche;

            // Calcular porcentaje de descuento
            if (reservacion.FormaPago.Equals("Card"))
            {
                reservacion.DescuentoPorcentaje = 0;

            }
            else
            {
                var descuentoPorcentaje = CalcularDescuento(reservacion.Noches);
                reservacion.DescuentoPorcentaje = descuentoPorcentaje;
            }
      

            // Total con descuento
            reservacion.TotalConDescuento = reservacion.TotalSinDescuento * (1 - (reservacion.DescuentoPorcentaje / 100));

            // Agregar IVA
            const decimal IVA = 13;
            decimal totalFinalConIVA = reservacion.TotalConDescuento * (1 + IVA / 100);
            

            // Calcular otros valores
            reservacion.Prima = reservacion.TotalConDescuento * (paquete.PrimaPorcentaje / 100);
            reservacion.RestoEnMensualidades = (reservacion.TotalConDescuento - reservacion.Prima) / paquete.Mensualidades;

            var tipoCambio = await httpClient.GetAsync("https://apis.gometa.org/tdc/tdc.json");
            if (tipoCambio.IsSuccessStatusCode)
            {
                var content = await tipoCambio.Content.ReadAsStringAsync();
                dynamic data = JObject.Parse(content);
                reservacion.TipoCambio = data.venta;
            }


            reservacion.TotalUSD = totalFinalConIVA / reservacion.TipoCambio;
            int userId = int.Parse(User.FindFirstValue("UserId"));
            reservacion.ClienteID = userId;
            reservacion.ReservacionID = 2;
            reservacion.PaqueteID = id;



            TempData["TotalFinal"] = "El total seria de "+totalFinalConIVA;
           


            return View(reservacion);
            

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind] Reservacion reservacion)
        {
            //El ID de la reservacion se genera de forma automatica
            reservacion.ReservacionID = 0;
            int userId = int.Parse(User.FindFirstValue("UserId"));
            reservacion.ClienteID = userId;
            httpClient.DefaultRequestHeaders.Authorization = AutorizacionToken();



            //Se utiliza la API web  para almacenar los datos de la reservacion
            var agregar =  httpClient.PostAsJsonAsync<Reservacion>("/Reservaciones/Agregar", reservacion);

            await agregar;  //se espera que termine la transacción

            var resultado = agregar.Result;

            if (resultado.IsSuccessStatusCode) //si todo fue correcto
            {
                //se ubica al usuario dentro del listado de reservaciones
                return RedirectToAction("Index","Clientes");
            }
            else
            {
                TempData["Mensaje"] = "No se logró registrar la reservacion..";
                return View(reservacion);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            httpClient.DefaultRequestHeaders.Authorization = AutorizacionToken();

            HttpResponseMessage response = await httpClient.DeleteAsync($"/Reservaciones/Eliminar?id={id}");

            //se valida si durante la transaccion el token expiro
            if (response.StatusCode.ToString().Equals($"Reservacion no eliminada, el id {id} no existe"))
            {
                return RedirectToAction("Login", "Usuarios");
            }
            else
            {
                TempData["Delete"] = "Reservation deleted correctly";
                return Redirect(Url.Action("Index", "Clientes") + "#reservations");

            }
        }

        private AuthenticationHeaderValue AutorizacionToken()
        {
            //se extrae el token almacenado dentro de la sesión
            var token = HttpContext.Session.GetString("token");

            //Variable para almacenar el token de autenticación
            AuthenticationHeaderValue authentication = null;

            if (token != null && token.Length != 0)
            {
                //Se almacena el token  otorgado por la API
                authentication = new AuthenticationHeaderValue("Bearer", token);
            }

            //se retorna la información
            return authentication;
        }

        [HttpGet]

        public async Task<IActionResult> Update(int id)
        {
            HttpResponseMessage responseReservacion = await httpClient.GetAsync($"/Reservaciones/Buscar?id={id}");
            Reservacion reservacion = null;

AppWebBeachSA/Views/Empleados/CrearCuenta.cshtml
@model AppWebBeachSA.Models.Empleado

@{
    ViewData["Title"] = "CrearCuenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body style="background-color:#413E3E">
    <section class="d-flex align-items-center justify-content-center min-vh-100">
        <div class="container py-4">
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="card shadow-lg d-flex flex-row border-0" style="border-radius: 1rem;">
                        <div class="col-md-7 p-4">
                            <div class="card-body text-black">
                                <form asp-action="CrearCuenta" id="FormularioLogin">
                                    @if (TempData["Error"] != null)
                                    {
                                        <div class="alert alert-warning" role="alert">
                                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            <strong>@TempData["Error"]</strong>
                                        </div>
                                    }
                                    <h2 class="fw-bold mb-3 pb-3" style="letter-spacing: 1px;">Create Your Account employee!!!</h2>

                                    <div class="row">
                                        <div class="form-group">
                                            <label asp-for="Nombre" class="form-label">Name</label>
                                            <input asp-for="Nombre" class="form-control" />
                                            <span asp-validation-for="Nombre" class="text-danger"> </span>
                                        </div>

                                        <div class="form-group">
                                            <label asp-for="Email" class="form-label mt-3">Email</label>
                                            <input asp-for="Email" class="form-control" placeholder="test@AppDomain.com" />
                                            <span asp-validation-for="Email" class="text-danger"> </span>
                                        </div>

                                        <div class="form-group">
                                            <label asp-for="Password" class="form-label mt-3">Password</label>
                                            <input asp-for="Password" class="form-control" />
                                        </div>

                                        <div class="form-group">
                                            <label class="form-label mt-3">Confirm Password</label>
                                            <input name="confirmPassword" class="form-control" type="password" />
                                            <span asp-validation-for="Password" class="text-danger"> </span>
                                        </div>

                                    </div>

                                    <div class="form-group mb-4 mt-4">
                                        <input type="submit" value="Create" class="btn btn-dark btn-lg w-100" />
                                    </div>

                                    <a class="small text-muted" href="#!">Forgot password?</a>
                                    <p class="mt-3" style="color: #393f81;">
                                        Do you already have an account? <a asp-controller="Empleados" asp-action="Login">Login.</a>
                                    </p>
                                </form>
                            </div>
                        </div>
                        <div class="col-md-5 d-none d-md-block">
                            <img src="https://static.misionesonline.news/wp-content/uploads/2017/08/16_tres-empleados-juntando-sus-manos-4ba6fvno53g0.jpg"
                                 alt="Login Form" class="img-fluid w-100 h-100" style="border-radius: 0 1rem 1rem 0; object-fit: cover;" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

AppWebBeachSA/Views/Empleados/Home.cshtml
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Employee Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" rel="stylesheet">
    <style>

        header h1 {
            font-size: 2.5rem;
        }

        header p {
            font-size: 1.2rem;
        }

        section {
            margin-bottom: 5rem;
        }

            section h2 {
                margin-bottom: 2rem;
            }


        .card-hover {
            transition: transform 0.4s ease, box-shadow 0.4s ease;
            z-index: 0;
        }

            .card-hover:hover {
                transform: scale(1.05);
                box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
                z-index: 1;
            }


        .dashboard-btn {
            font-size: 1.3rem;
            padding: 15px 20px;
            text-align: center;
        }

        .btn-lg {
            font-size: 1.4rem;
            padding: 15px 25px;
        }


        .list-group-item .badge {
            font-size: 1.2rem;
            padding: 8px 16px;
        }

        .list-group-item {
            font-size: 1.1rem;
        }
    </style>
</head>
<body>

    <header class="bg-primary text-white text-center py-4">
        <div class="container">
            <h1 class="display-5 fw-bold">Employee Dashboard</h1>
            <p class="lead">Manage reservations, packages, and hotel operations efficiently</p>
        </div>
    </header>

    <main class="container">
        <div class="row g-4 mt-3">
            <div class="col-md-6" data-aos="zoom-in">
                <div class="card border-0 shadow card-hover">
                    <div class="card-body text-center">
                        <i class="bi bi-box-seam display-4 text-primary mb-3"></i>
                        <h5 class="card-title section-title">Manage Packages</h5>
                        <p class="card-text text-muted">Add, edit, or delete hotel packages for your customers.</p>
                        <a asp-action="Index" asp-controller="Paquetes" class="btn btn-primary dashboard-btn">Go to Packages</a>
                    </div>
                </div>
            </div>

            <div class="col-md-6" data-aos="zoom-in" data-aos-delay="200">
                <div class="card border-0 shadow card-hover">
                    <div class="card-body text-center">
                        <i class="bi bi-calendar-event display-4 text-success mb-3"></i>
                        <h5 class="card-title section-title">Manage Reservations</h5>
                        <p class="card-text text-muted">View customer reservations.</p>
                        <a asp-action="Listado" asp-controller="Reservaciones" class="btn btn-success dashboard-btn">Go to Reservations</a>
                    </div>
                </div>
            </div>
        </div>

        <section data-aos="fade-up">
            <h2 class="text-center section-title mt-3">Employee Statistics</h2>
            <div class="row g-4 text-center">
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm card-hover">
                        <div class="card-body">
                            <i class="bi bi-people display-4 text-warning mb-3"></i>
                            <h5 class="section-title">Active Employees</h5>
                            <p class="fs-4 fw-bold">@ViewBag.EmployeeCount</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm card-hover">
                        <div class="card-body">
                            <i class="bi bi-calendar2-check display-4 text-info mb-3"></i>
                            <h5 class="section-title">Completed Reservations</h5>
                            <p class="fs-4 fw-bold">@ViewBag.ReservationCount</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm card-hover">
                        <div class="card-body">
                            <i class="bi bi-box display-4 text-danger mb-3"></i>
                            <h5 class="section-title">Packages Available</h5>
                            <p class="fs-4 fw-bold">@ViewBag.PackageCount</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section data-aos="fade-up">
            <h2 class="text-center section-title">Notifications</h2>
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    New reservation by John Doe for Deluxe Room
                    <span class="badge bg-primary rounded-pill">View</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Package "Weekend Getaway" has been updated
                    <span class="badge bg-warning text-dark rounded-pill">Details</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Reminder: Staff meeting at 3 PM
                    <span class="badge bg-success rounded-pill">Dismiss</span>
                </li>
            </ul>
        </section>

        <section class="text-center" data-aos="fade-up">
            <h2 class="section-title">Quick Actions</h2>
            <div class="d-flex flex-wrap justify-content-center gap-3">
                <button class="btn btn-outline-primary btn-lg">
                    <i class="bi bi-person-plus me-2"></i>Add Employee
                </button>
                <button class="btn btn-outline-danger btn-lg">
                    <i class="bi bi-boxes me-2"></i>Update Inventory
                </button>
                <button class="btn btn-outline-success btn-lg">
                    <i class="bi bi-card-checklist me-2"></i>Generate Report
                </button>
            </div>
        </section>

        <section data-aos="fade-up">
            <h2 class="text-center section-title">Gallery Management</h2>
            <p class="text-center text-muted mb-4">Upload and manage images to showcase your hotel.</p>

            <div class="row g-4 justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 shadow card-hover">
                        <div class="card-body text-center">
                            <i class="bi bi-cloud-upload display-4 text-primary mb-3"></i>
                            <h5 class="card-title section-title">Upload Image</h5>
                            <p class="card-text text-muted">Add new images to the gallery for your customers.</p>
                            <input type="file" class="form-control mb-3" accept="image/*">
                            <button class="btn btn-primary dashboard-btn">Upload</button>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-8">
                    <div class="row g-3">
                        <div class="col-6 col-sm-4">
                            <div class="card border-0 shadow-sm">
                                <img src="https://via.placeholder.com/150" class="card-img-top" alt="Image 1">
                                <div class="card-body text-center">
                                    <button class="btn btn-danger btn-sm w-100">
                                        <i class="bi bi-trash3 me-1"></i>Remove
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-6 col-sm-4">
                            <div class="card border-0 shadow-sm">
                                <img src="https://via.placeholder.com/150" class="card-img-top" alt="Image 2">
                                <div class="card-body text-center">
                                    <button class="btn btn-danger btn-sm w-100">
                                        <i class="bi bi-trash3 me-1"></i>Remove
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
    <script>
        AOS.init({
            duration: 1000,
            once: true,
            offset: 120
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>